# Generated by Django 4.0.3 on 2022-03-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='musiclist',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
