# Generated by Django 4.0.3 on 2022-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_musiclist_name_alter_musiclist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='musiclist',
            name='keeping',
            field=models.ManyToManyField(to='musicapp.tag'),
        ),
    ]
