# Generated by Django 4.0.3 on 2022-03-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
